version: '3.8'

services:
  # Trino Coordinator (Master)
  trino-coordinator:
    image: trinodb/trino:423
    container_name: trino-coordinator
    ports:
      - "8081:8080"
    volumes:
      - ../docker/trino/etc:/etc/trino
      - ../docker/trino/etc/catalog/minio.properties:/etc/trino/catalog/minio.properties
      # - ../docker/spark/lib/delta-core_2.12-2.2.0.jar:/usr/lib/trino/plugin/hive/delta-core_2.12-2.2.0.jar
      # - ../docker/spark/lib/delta-storage-2.2.0.jar:/usr/lib/trino/plugin/hive/delta-storage-2.2.0.jar
      # - ../docker/trino/trino-delta-lake-423.jar:/usr/lib/trino/plugin/deltalake/trino-delta-lake-423.jar
      # - ../docker/trino/etc/jvm.config:/etc/trino/jvm.config
      # - ../docker/trino/etc/node.properties:/etc/trino/node.properties
      # - ../docker/spark/lib/hadoop-aws-3.2.0.jar:/usr/lib/trino/plugin/hive/hadoop-aws-3.2.0.jar
      # - ../docker/spark/lib/aws-java-sdk-bundle-1.11.375.jar:/usr/lib/trino/plugin/hive/aws-java-sdk-bundle-1.11.375.jar
    environment:
      - TRINO_NODE_TYPE=coordinator
    networks:
      - data_platform_network

  # Trino Worker 1
  trino-worker-1:
    image: trinodb/trino:423
    container_name: trino-worker-1
    depends_on:
      - trino-coordinator
    volumes:
      - ../docker/trino/etc/node.properties:/etc/trino/node.properties
    environment:
      - TRINO_NODE_TYPE=worker
    networks:
      - data_platform_network

  # Trino Worker 2 (Optional)
  trino-worker-2:
    image: trinodb/trino:423
    container_name: trino-worker-2
    depends_on:
      - trino-coordinator
    volumes:
      - ../docker/trino/etc/node.properties:/etc/trino/node.properties
    environment:
      - TRINO_NODE_TYPE=worker
    networks:
      - data_platform_network

  # Trino Test Client
  trino-test:
    image: trinodb/trino:423
    container_name: trino-test
    depends_on:
      - trino-coordinator
    volumes:
      - ../docker/trino/test-trino.sh:/test-trino.sh
      - ../docker/trino/trino-delta-lake-423.jar:/usr/lib/trino/plugin/deltalake/trino-delta-lake-423.jar
    entrypoint: ["/bin/bash", "/test-trino.sh"]
    networks:
      - data_platform_network
    restart: on-failure

networks:
  data_platform_network:
    external: true
