version: '3.8'

services:
  # Redis for Superset caching
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - data_platform_network

  # Apache Superset for Dashboards
  superset:
    image: apache/superset:latest
    container_name: superset
    depends_on:
      - redis
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      PYTHONPATH: /app/superset_home
      SUPERSET_CONFIG_PATH: /app/superset_config.py
      SUPERSET_FEATURE_DREMIO: "true"
    volumes:
      - ../docker/superset/config/superset_config.py:/app/superset_config.py
      - ../docker/superset/config/datasources.yml:/app/datasources.yml
      - ../docker/superset/init-superset.sh:/app/init-superset.sh
      - superset_data:/app/superset_home
    command: ["/bin/bash", "-c", 
              "pip install --force-reinstall pillow trino==0.321.0 sqlalchemy-trino==0.4.0 sqlalchemy==1.4.46
               && chmod +x /app/init-superset.sh 
               && /app/init-superset.sh ${SUPERSET_ADMIN_USERNAME} ${SUPERSET_ADMIN_PASSWORD}
               && /usr/bin/run-server.sh"
             ]
    networks:
      - data_platform_network

  # Superset Test Client
  superset-test:
    image: curlimages/curl:latest
    container_name: superset-test
    depends_on:
      - superset
    volumes:
      - ../docker/superset/test-superset.sh:/test-superset.sh
    entrypoint: ["/bin/sh", "/test-superset.sh"]
    networks:
      - data_platform_network
    restart: on-failure

networks:
  data_platform_network:
    external: true

volumes:
  superset_data:
    external: true
