services:
  postgres:
    image: postgres:13
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data 
    volumes:
      - pg_data:/var/lib/postgresql/pg_data
    networks:
      - data_platform_network

volumes:
  pg_data:
    external: true
networks:
  data_platform_network:
    external: true
